name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies...
        run: npm i
        shell: bash
      - name: Clean installing...
        run: npm ci
        shell: bash
      - name: Building...
        run: npm run build
        shell: bash
      - run: git config user.name github-actions
        shell: bash
      - run: git config user.email github-actions@github.com
        shell: bash
      - run: git --work-tree build add --all
        shell: bash
      - name: Creating deploy commit...
        run: git commit -m "Automatic deploy - `date +'%Y-%m-%d %H:%M:%S'`"
        shell: bash
      - name: Deploying to GitHub Pages
        run: git push origin HEAD:gh-pages --force
        shell: bash