name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies...
        run: npm i
        shell: bash
      - name: Testing...
        run: npm run test -- --watchAll=false --reporters=default --reporters=jest-junit --coverage  --coverageReporters=cobertura
        shell: bash
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          files: ./junit.xml
          flags: unittests
          name: wilde-codecov
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: MpStyle/wilde